---
- name: clone rfcat repository
  git: 
    repo: https://github.com/atlas0fd00m/rfcat.git
    dest: /opt/rfcat
    version: master

- name: install jedi
  pip:
    name: jedi<0.18.0

- name: install packages from the requirements.txt
  pip:
    requirements: /opt/rfcat/requirements.txt

- name: symbolically link rfcat
  file:
    src: /opt/rfcat/rfcat 
    dest: /usr/local/bin/rfcat
    state: link

- name: download and extract sdcc 3.5.0
  unarchive:
    src: https://sourceforge.net/projects/sdcc/files/sdcc/3.5.0/sdcc-src-3.5.0.tar.bz2
    dest: /opt
    remote_src: yes

- name: compile and install sdcc
  shell: |
    cd /opt/sdcc-3.5.0
    ./configure
    make && make install

- name: enable usb access without elevated privileges
  lineinfile:
    create: yes
    group: root
    line: 'SUBSYSTEM=="usb",MODE="0666"'
    mode: '0644'
    owner: root
    path: /etc/udev/rules.d/usb.rules
    regexp: 'SUBSYSTEM=="usb",MODE="0666"'
...
