---

- name: update apt cache
  apt: 
    update_cache: yes
  
- name: install apt packages
  apt: 
    name: "{{ item }}"
    state: present 
  loop: "{{ apt_packages }}"
  ignore_errors: yes

- name: "create VirtualBox group for user: {{ username }}"
  group:
    name: vboxusers
    state: present

- name: "create user account for user: {{ username }}"
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    groups: 
        - vboxusers
        - cdrom 
        - floppy
        - sudo
        - audio
        - dip
        - video
        - plugdev
        - netdev
        - dialout
    expires: -1

- name: remove old dotfiles
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/home/{{ username }}/.zshrc"
    - "/home/{{ username }}/.vimrc"

- name: clone dotfiles
  git:
    repo: 'https://github.com/Loumiakas/dotfiles.git'
    dest: "/home/{{ username }}/.dotfiles"
    clone: yes
    update: yes
  become: yes
  become_user: "{{ username }}"

- name: install dotfiles
  shell: "/home/{{ username }}/.dotfiles/setup.sh"
  become: yes
  become_user: "{{ username }}"

...
