---

- name: update apt cache
  apt: 
    update_cache: yes
  
- name: install apt packages
  apt: 
    name: "{{ item }}"
    state: present 
  loop: "{{ apt_packages }}"
  ignore_errors: yes
    
- name: install pip packages
  pip: 
    name: "{{ item }}"
    state: present 
  loop: "{{ pip_packages }}"
  ignore_errors: yes

- name: create nrf sniffer directory
  file:
    path: /opt/nrf
    state: directory
    mode: '0655'
    owner: root
    group: root

- name: download and extract nrf.zip into /opt/nrf
  unarchive:
    src: "{{ nrf_sniffer_link }}"
    dest: /opt/nrf
    remote_src: yes

- name: install nrf command line tools
  apt:
    deb: "{{ nrf_cmd_line_tools_link }}"

- name: copy wireshark configuration files
  shell: |
    if [ ! -d /usr/lib/x86_64-linux-gnu/wireshark/extcap/SnifferAPI ]; then
      cp -r /opt/nrf/extcap/*  /usr/lib/x86_64-linux-gnu/wireshark/extcap
    fi
    if [ ! -d  /usr/share/wireshark/profiles/Profile_nRF_Sniffer_Bluetooth_LE ]; then
      cp -r /opt/nrf/Profile_nRF_Sniffer_Bluetooth_LE  /usr/share/wireshark/profiles
    fi

- name: enable tty access without elevated privileges
  lineinfile:
    create: yes
    group: root
    line: 'SUBSYSTEM=="tty",MODE="0666"'
    mode: '0644'
    owner: root
    path: /etc/udev/rules.d/usb.rules
    regexp: 'SUBSYSTEM=="tty",MODE="0666"'

...
