---

- name: update apt cache
  apt: 
    update_cache: yes
  
- name: install apt packages
  apt: 
    name: "{{ item }}"
    state: present 
  loop: "{{ apt_packages }}"
  ignore_errors: yes

- name: enable bluetooth headset pairing on the system
  lineinfile:
    path: /etc/bluetooth/main.conf
    insertafter: '#*ControllerMode*'
    line: 'ControllerMode = bredr'

- name: install arduino-cli
  shell: |
    curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
    warn: false
  ignore_errors: yes
...
